(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[302,153,92,184],[120,252,95,69],[396,255,95,61],[302,0,137,151],[0,252,118,85],[396,153,109,100],[0,0,300,250]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.cinamonrolls = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.cranberriesshadow = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.fruitorangebowl = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.greenvegetables = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.potatoesshadow = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.potatoeswellmakethefeast = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.squareholidaymainstable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.youtakethecredit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgFAGQgCgDAAgDQAAgCACgDQACgCADAAQAEAAACACQACADAAACQAAADgCADQgCACgEAAQgDAAgCgCg");
	this.shape.setTransform(69.4,1.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AABApIgCAAIgDgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAg7QAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAIgDgBIgHAAIgGAAIgDAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgBgEIAAgCIAAgDIABgCIADgBIA4AAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABIAAADIAAADIAAADIgBACIgDABIgQAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIABA7IgBADIgDABg");
	this.shape_1.setTransform(64,-2.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgCAqQgDAAgCgCIAAhPIACgCIADAAIACAAIADAAQADAAACADIAABNIgCACIgDABIgDAAg");
	this.shape_2.setTransform(58.7,-2.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgiApIgDgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhJQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBIADgBIAeAAIAIABIAIACQAIADAGAFQAGAGAEAHIACAIIABAIQAAAJgDAIIgEAHIgGAGIgGAEIgIAEQgIADgIAAgAgWgYIgBADIAAAsQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABABIADABIAOAAQAFAAAFgCQAGgCAEgEQAEgDACgFQACgFAAgGQAAgFgCgFQgCgFgEgDQgEgEgGgCQgFgBgFAAIgOAAIgEABg");
	this.shape_3.setTransform(52.3,-2.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgbApIgCgBIgCgCIAAhLQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIACgBIA5AAIACACIAAACIAAADIAAACIAAADIgCADIgqAAIgCABIgBACIAAALIABADIACABIAbAAIABABIABADIAAADIAAACQAAADgCABIgbAAIgCACIgBACIAAANIABADIACABIAqAAQACABAAADIAAADIAAADIgBADIgCABg");
	this.shape_4.setTransform(43.6,-2.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AAUAqIgCgBIgBgBIgBgBIgOgWIgCgCIgDgBIgLAAIgDABQAAAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAIgDABIgDABIgCAAIgFgBQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhKIABgDIADgBIAiAAQAGABAGACQAFABAEAEQADAEADAEQACAGAAAGQAAAHgCAFIgGAGIgGADQgBABAAAAQgBABAAAAQAAABAAAAQAAABgBAAIAAACIADAEIAGAHIADAHIADAEIgCACIgCACIgDABIgDABgAgQgaQAAABgBAAQAAAAgBABQAAAAAAABQAAAAAAABIAAASQAAABAAAAQAAABAAAAQABABAAAAQABAAAAABIAEAAIAPAAIAGAAIAGgCIADgFIABgGQAAgGgEgEIgGgDIgGgBIgPAAIgEABg");
	this.shape_5.setTransform(35.2,-2.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgDAqIgIgDIgHgDIgHgGIgFgFIgEgIQgEgHAAgKQAAgIAEgIIAEgHIAFgGQAGgGAIgDIAIgDIAIgBIAJABIAKAEIAIAEIAGAHIABABQAAABAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgDADIgDABIgCABIgDgBIgFgFIgGgEQgEgBgGAAQgFAAgFACQgFACgEAFQgDADgDAGQgCAEAAAFQAAAGACAFIAGAJQAEAEAFACQAFADAFgBQAGABAGgDQAGgDAEgEIACgBIADABIADACIACADIACACIgBABQgCAEgFADIgHAFIgJADIgKABIgIgBg");
	this.shape_6.setTransform(26.1,-2.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgbApIgCgBIgCgCIAAhLQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIACgBIA4AAIACACIABACIAAADIAAACIgBADIgCADIgqAAIgCABIgBACIAAALIABADIADABIAbAAIACABIABADIAAADIAAACQAAADgDABIgaAAIgEACIgBACIAAANIABADIADABIApAAQADABAAADIAAADIAAADIgBADIgCABg");
	this.shape_7.setTransform(14.4,-2.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AAWApIgDgBIAAgdQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAIgDgBIgaAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAAAAAABIAAAcQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAIgDABIgDAAIgDAAIgDgBIgCgCIAAhOIACgBIADgBIADAAIADAAQADAAACADIAAAaIABADQAAAAAAABQABAAAAAAQAAAAABAAQAAABAAAAIAcAAIADgCQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAgBIAAgaQABgDADAAIAFAAIADABIADACIAABNQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgFABg");
	this.shape_8.setTransform(5.4,-2.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AABApIgCAAIgDgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAg7QAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAIgDgBIgHAAIgGAAIgDAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgBgEIAAgCIAAgDIABgCIADgBIA4AAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABIAAADIAAADIAAADIgBACIgDABIgQAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIABA7IgBADIgDABg");
	this.shape_9.setTransform(-2.7,-2.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AgbApIgCgBIgCgCIAAhLQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIACgBIA4AAIADACIAAACIAAADIAAACIAAADIgDADIgpAAIgDABIgBACIAAALIABADIADABIAbAAIACABIAAADIAAADIAAACQAAADgCABIgaAAIgEACIgBACIAAANIABADIADABIApAAQADABAAADIAAADIAAADIgBADIgCABg");
	this.shape_10.setTransform(-13.4,-2.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AATAqIgDgCIgUgfIgCgCIgEAAIgEABQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAAaIgBADIgEABIgDAAIgDAAQgEAAgBgEIAAhMIACgCIADgBIADAAIACAAQAEAAACADIAAAaQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAIADABQABAAAAAAQABAAAAgBQABAAAAAAQABgBAAAAIAWgcIACgBIACAAIACABIADABIADADIABACIAAACIgVAXIgBACIAAACIAAACIABACIAaAjIAAABIAAABIgBACIgCACIgEABIgDABg");
	this.shape_11.setTransform(-21.5,-2.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AAeApIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAIgEgLIgCgCIgCgBIgbAAIgBABIgBAAIgBABIgBABIgEALIgCACIgCAAIgDABIgCAAIgCAAIgCAAIgDgBIgBgBIAihNQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIACAAIADAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAhBMIAAABIgBABIgDABIgDAAgAgBgLIgBACIgBAEIgDAFIgBAEIgCADIAAACIAAACIACABIAPAAIACgBIABgCIgCgEIgCgGIgDgGIgCgFIgCAAIAAAAg");
	this.shape_12.setTransform(-30,-2.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AABApIgCAAIgDgBQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAg7QAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAIgDgBIgHAAIgGAAIgDAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgBgEIAAgCIAAgDIABgCIADgBIA4AAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABIAAADIAAADIAAADIgBACIgDABIgQAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIABA7IgBADIgDABg");
	this.shape_13.setTransform(-37.6,-2.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgNAoQgHgDgFgFQgFgEgCgGIgDgIIAAgHIAAgVIAAgXIABgDIADAAIADgBIACAAIAEABQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAqQAAAFABAEIAEAIIAHAFQAEACAEAAQAFAAAEgCQAEgCADgDIAEgIQABgEAAgFIAAgpQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABAAIAEgBIADAAIADAAIACABIABADIAAAsIgBAHIgCAIQgDAGgEAEQgFAFgHADQgGACgIAAQgHAAgGgCg");
	this.shape_14.setTransform(-49.4,-2.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgIAqIgIgDIgIgDIgGgGQgGgFgEgIIgCgIIgBgJIABgIIACgIQAEgHAGgGIAGgFIAIgEIAIgDIAIgBIAJABIAIADQAIADAGAGQAGAGADAHQAEAIAAAIIgBAJIgDAIQgDAIgGAFQgGAGgIADIgIADIgJABIgIgBgAgKgZIgJAGQgEAEgCAFQgCAFAAAFQAAAGACAFQACAFAEAEQAEAEAFACQAFADAFgBQAFABAFgDQAFgCAEgEQAEgEADgFQACgFAAgGQAAgFgCgFQgDgFgEgEIgJgGQgFgCgFAAQgFAAgFACg");
	this.shape_15.setTransform(-58.9,-2.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AgBArIgBAAIgCgBIgCgBIAAgBIAAgdIgBgFIgCgEIgYgkIAAgBIABgCIACgCIAEgCIADAAIACAAIACACIAQAbIACABIABABIACgBIABgBIARgbIACgCIADgBIACABIADABIADACIABACIAAABIgBABIgXAkIgCAFIAAACIgBABIAAAdQAAABAAABQgBAAAAABQgBAAAAAAQgBABAAAAg");
	this.shape_16.setTransform(-67.7,-2.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.youtakethecredit, new cjs.Rectangle(-73.4,-9.9,146.9,16), null);


(lib.whitesquare = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A41UyMAAAgpjMAxrAAAMAAAApjg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitesquare, new cjs.Rectangle(-158.9,-133,318,266), null);


(lib.wellmakethefeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgRASQgHgIAAgKQAAgKAHgHQAHgHAKAAQALAAAHAHQAHAHAAAKQAAAKgHAIQgIAHgKAAQgKAAgHgHg");
	this.shape.setTransform(53.2,25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgIBiQgIgDgGgFQgFgFgDgKQgCgJAAgXIAAhXIgPAAIgFgBIgBgFIAAgDQAAgGARgOIAGgGIAGgGQARgPAHABIAEABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAfIAlAAQAEgBABACQABACAAAEIAAAEQAAAEgBACQgCACgDAAIgiAAIgDABIgBAEIAABQQAAAVAEAFQAEAGAJAAQAFgBAIgCIALgDQAEABACACQACACABADQgBAJgOAIQgNAJgRgBQgKABgIgDg");
	this.shape_1.setTransform(43.1,17.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgLBUIgSgCIgFACIgFABIgDAAIgDgCQgGgFgEgNQgFgNAAgMQAAgGACgDQAEgEADABQAIAAAIAMIAGAKQAEAHAJADQAIAFAJAAQALgBAHgFQAFgGABgIQAAgOgbgNIgJgFQgagMgIgKQgKgLABgPQgBgVAPgNQAPgOAYAAIAKAAIAMADIAHgEIAGgBQAHABAIANQAHAMAAAPQABAFgDAEQgDADgEAAQgEAAgEgDQgDgEgFgIQgGgJgGgEQgHgFgJAAQgJAAgFAGQgGAFAAAIQAAAIAGAGQAFAGAUAKIACABQAtAVAAAaQAAAXgRAPQgSAQgagBg");
	this.shape_2.setTransform(30.1,19);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AAdBMIgIgIIgHAEQgUANgVAAQgXAAgPgOQgPgOAAgWQAAgaATgOQAUgPAhAAQAIAAAEADQAEACAAAHQAAAIgKABQgQAAgLAHQgJAIAAANQAAAOAJAHQAIAJAOgBQAPABAHgIQAHgHAAgRIAAg9QAAgOgHgIQgFgIgMABQgHAAgHADQgHAEgGAGIgEAFQgJAMgMAAQgGABgEgEQgEgFAAgHQAAgPATgLQATgKAdAAQASAAANAFQANAFAHAIQAFAGACAKQACALAAAXIAAA0QAAAIABAFQACAFADABIAFABQAKADAAAGQABAHgLAGQgMAHgOAAQgHAAgIgJg");
	this.shape_3.setTransform(14.7,19.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("Ag0A9QgYgYABgjQAAglAYgYQAXgZAkAAQAgAAASASQATASAAAeQAAAKgDAEQgEADgLAAIg+AAQgFAAgEgDQgCgDAAgEQAAgEACgCQAEgDAFAAIAhAAIAIgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAgBAAgBQAAgQgKgKQgLgLgOAAQgUAAgJARQgKARABAYQAAAYAMATQANASAVAAQALAAAIgCQAJgDAIgGIAFgEQAJgHAFAAQADAAACADQACACABADQAAAEgFAGQgDAFgIAGQgNAMgOAFQgNAFgPAAQgiAAgXgYg");
	this.shape_4.setTransform(-2.8,19.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AhSB1QgJgDAAgIQAAgGAJgDQAIgEACgCQACgDACgZIABg/IgCg7QgBgZgCgDQgCgDgIgDQgJgEAAgHQAAgGAIgCQAHgDAcAAIBjAAIAQgBIAIgCIAFABIACADQAEAGADALQADALAAAIQAAAHgDAEQgDAEgFAAQgFAAgHgLIgFgIQgDgFgHgDQgIgCgLAAIgWAAQgPAAgIACQgIABgDAEQgCADgCALIgBAfIAAANQAAAIABACQACACAEAAIAaAAQANAAAFgEQAFgDACgLIAAgCQADgRAJAAQAHAAACAIQADAJAAAgQAAAegDAIQgCAJgHAAQgJAAgDgRIAAgDQgBgKgGgEQgFgDgNAAIgZAAQgFAAgBACQgCADAAAKIAAANIABAuQABAJADACIAHAEQAKAEAAAHQAAAHgJADQgJACgZAAQgaAAgJgCg");
	this.shape_5.setTransform(-21,15.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("Ag0A9QgXgYAAgjQgBglAYgYQAYgZAkAAQAgAAASASQASASABAeQgBAKgDAEQgDADgLAAIg+AAQgGAAgCgDQgEgDAAgEQAAgEAEgCQACgDAGAAIAhAAIAIgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgQgLgKQgKgLgOAAQgUAAgJARQgKARAAAYQABAYANATQANASATAAQAMAAAJgCQAIgDAHgGIAGgEQAJgHAFAAQADAAACADQACACAAADQAAAEgEAGQgEAFgGAGQgOAMgOAFQgNAFgPAAQgiAAgXgYg");
	this.shape_6.setTransform(-48.5,19.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AAXB1QgIgDAAgGQAAgGAIgDIAGgDQAEgCABgHQACgHAAgRQAAg1gHgMQgHgNgRAAQgHAAgIAFQgIAFgEAIQgEAHgBANQgCAMAAAgQAAARACAFQABAFADACIAGADQAJADAAAGQAAAGgIADQgIACgVAAQgaAAgIgCQgIgDAAgHQAAgFAIgDIAFgCQAEgDACgHQACgGAAgSIAAgbIAAgYIgBhKQgBgSgDgDQgCgCgJgDQgKgDAAgFQAAgFAEgDQAEgDAPgFIAQgFIAPgBQAFAAADADQACADAAAHIgBAHIgBBBIAAAIIABAEIACABIAEgEIAGgGQAIgIAJgEQAIgEAKAAQAcAAAOASQAOASAAAkIAAAPIAAAdIAAAJQAAAIACAEQABADAEADIAEABQAIADAAAGQAAAHgIADQgIACgZAAQgVAAgIgCg");
	this.shape_7.setTransform(-67.1,15.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgIBiQgIgDgGgFQgFgFgDgKQgCgJAAgXIAAhXIgPAAIgFgBIgBgFIAAgDQAAgGARgOIAGgGIAGgGQASgPAGABIAEABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAfIAkAAQAEgBACACQACACgBAEIAAAEQABAEgCACQgCACgEAAIghAAIgDABIgBAEIAABQQAAAVAEAFQADAGAKAAQAFgBAIgCIALgDQAEABACACQACACABADQgBAJgOAIQgNAJgRgBQgKABgIgDg");
	this.shape_8.setTransform(-82.1,17.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("Ag0A9QgXgYgBgjQAAglAZgYQAXgZAlAAQAfAAASASQASASAAAeQAAAKgCAEQgDADgNAAIg+AAQgEAAgEgDQgCgDAAgEQAAgEACgCQAEgDAEAAIAiAAIAIgBQAAgBABAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgQgKgKQgLgLgPAAQgSAAgKARQgJARAAAYQgBAYANATQAOASATAAQANAAAHgCQAJgDAHgGIAHgEQAIgHAEAAQAEAAACADQADACgBADQAAAEgDAGQgFAFgHAGQgOAMgNAFQgNAFgQAAQghAAgXgYg");
	this.shape_9.setTransform(69.1,-16);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AA1B3IgHgBQgHgCgPgVIgHgJIgDgDQgngzgDAAQgBAAAAAAQgBAAAAAAQAAABAAAAQgBAAAAAAIAAAHIAAAIIABAiQABAKACACIAJAFQAIADAAAGQAAAGgIADQgJACgVABQgZgBgHgCQgIgDAAgHQAAgGAIgDIAEgBQAEgCACgJQACgHAAgUIAAgTIgBgaIAAgTIAAg9QgCgPgCgDQgCgBgHgCIgGgCIgGgDIgBgEQAAgFADgCQADgDAMgEIAWgGIARgDQAEAAACAEQADACAAAJIgBAeIgBArIAAAoIAAAIQABABAAAAQAAAAAAAAQABABAAAAQAAAAABAAIAHgEIALgKIAQgPQAEgFAAgCQAAgCgGgDQgFgDAAgFQAAgHAHgDQAJgDAXAAQAPAAAHADQAIADAAAGQAAAIgMADQgMADgFADQgGAEgOANIgCACIgGAGIgBADQAAAEAOASIABADIAcAiQAMANAGAFQAEADALACQAKAEAAAGQAAAIgHACQgIAEgRAAg");
	this.shape_10.setTransform(51.9,-19.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AAdBMIgIgIIgIAEQgUANgUAAQgXAAgPgOQgOgOAAgWQgBgaAUgOQASgPAjAAQAHAAAEADQAEACAAAHQAAAIgLABQgPAAgLAHQgJAIAAANQAAAOAIAHQAJAJAPgBQAOABAHgIQAHgHAAgRIAAg9QAAgOgHgIQgFgIgMABQgHAAgHADQgHAEgHAGIgDAFQgJAMgMAAQgGAAgEgDQgEgFAAgHQAAgPATgLQATgKAdAAQASAAANAFQAMAFAIAIQAFAGACAKQACALAAAXIAAA0QAAAIABAFQACAFADABIAFABQALADgBAGQAAAHgLAGQgLAHgOAAQgHAAgIgJg");
	this.shape_11.setTransform(33.8,-16);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AA9BzQgJgDAAgHQAAgHAKgEIAHgDQADgDABgGQABgIAAgVIAAgJIAAhFIAAgpIgVA2QgwB8gKAAQgFAAgKgRQgJgRgWg1IgkhRIgBBAIgBArIABAfQABAHACACIAHADQALAEgBAHQABAGgJADQgIAEgUAAQgSAAgIgEQgIgCAAgIQAAgFAJgFQAJgDABgEQACgHADgqQACgpAAg0IAAgFQAAgRgCgGQgBgGgEgCIgHgEQgLgDAAgHQAAgGAHgDQAIgCAYAAIAWAAIAHACQADACAMAdIAJAXIAEALQAoBhADAAQADABAPgkQAPghAUg6IACgKQAHgSAEgFQADgDAGgBIAXgBQAWAAAHACQAHADABAGQAAAHgKADIgFACQgFADgBAGQgCAGAAAaIACBcQABApACAGQABAEAIACIACACIAHAEQACACAAAEQAAAHgJADQgJACgbABQgYgBgJgCg");
	this.shape_12.setTransform(10.1,-19.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AgaB1QgIgDAAgHQgBgFAHgDIAIgFQADgCACgKIABggIAAgaIgBgdIAAgNQAAgpgBgLQgCgMgDgDIgKgDQgKgDAAgFQAAgFADgCQADgDAMgEIAVgGIAQgDQAFAAACAEQADACgBAJIAAAMQgCA5AAA7IABA3QABAMADADIAJAFQAIADgBAGQAAAGgIADQgIACgVABQgYgBgHgCg");
	this.shape_13.setTransform(-18.3,-19.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgbB1QgHgDAAgHQgBgFAHgDIAIgFQADgCACgKIABggIAAgaIgBgdIAAgNQAAgpgBgLQgBgMgEgDIgKgDQgKgDAAgFQgBgFAEgCQADgDAMgEIAVgGIAQgDQAFAAACAEQADACgBAJIAAAMQgCA5AAA7IABA3QABAMADADIAJAFQAHADAAAGQABAGgJADQgIACgVABQgYgBgIgCg");
	this.shape_14.setTransform(-27.4,-19.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgCAwIgLhHIAAgDIgBgEQAAgHAEgFQAEgEAGgBQAHABAEAEQAEAEAAAIIAAAFIAAACIgMBHg");
	this.shape_15.setTransform(-34.5,-26.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("Ag0A9QgXgYAAgjQgBglAYgYQAYgZAkAAQAgAAASASQASASABAeQgBAKgDAEQgDADgLAAIg+AAQgGAAgCgDQgEgDAAgEQAAgEAEgCQACgDAGAAIAhAAIAIgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgQgLgKQgKgLgOAAQgUAAgJARQgKARAAAYQABAYANATQANASATAAQAMAAAJgCQAIgDAHgGIAGgEQAJgHAFAAQADAAACADQACACAAADQAAAEgEAGQgEAFgGAGQgOAMgOAFQgNAFgPAAQgiAAgXgYg");
	this.shape_16.setTransform(-45.8,-16);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006F46").s().p("AAWA5IgihaQgLgdgGgOQgHgNgGgFIgJgEQgIgDAAgGQAAgHAIgCQAHgDAfAAQAeAAAHADQAIACAAAHQAAAGgMAFIgCABQgDABgCACQgCADAAADQAAAGAIAWIAbBHIALAaQAEAHACAAQACAAAEgGIAKgYIADgGQAihRAAgKQAAgFgCgDQgDgEgFgCIgEgCQgKgEAAgGQAAgHAHgCQAGgDAbAAQAaAAAGADQAHACAAAHQAAAGgJAEIgHAEQgLAHgWA4IgOAhIgfBNIgFAOQgKAagHAAQgJAAgYg/gAhDBqIgCgFQgVgtgfhTIgPgnIgKgUQgEgGgFgDIgFgCQgKgDAAgHQAAgHAHgCQAIgDAfAAQAfAAAHADQAIACAAAHQAAAGgNAFIgBAAIgGAEQgCADAAADQAAAGAHATIAbBHIANAeQADAGADAAQACAAAEgIIAIgTQAEgLAIAAQALAAAAALIgDAKIgVA0IgEAMQgLAbgGAAQgGAAgGgOg");
	this.shape_17.setTransform(-71.2,-19.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakethefeast, new cjs.Rectangle(-90,-43,169.8,79.7), null);


(lib.wellmake = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape.setTransform(76.7,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AA4B/IgHgCQgHgDgRgUIgHgKIgDgEQgqg2gDAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAIAAAHIAAAHIABAlQABAKACAEIAKAEQAIADAAAHQAAAGgJADQgIADgXAAQgaAAgIgDQgJgDAAgHQAAgGAJgDIAEgCQAFgCACgJQABgIAAgUIAAgWIAAgbIAAgUIgBhAQgBgRgDgCQgCgDgHgCIgGgBIgHgDIgBgGQAAgEADgDQAEgDAMgEIAXgGIASgDQAFAAACAEQADACAAAJIgBAhIgBAtIAAArIAAAJQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAHgEIANgKIAQgRQAEgEAAgDQAAgBgGgEQgFgDAAgFQAAgJAIgCQAJgEAYAAQAQAAAIAEQAIADAAAHQAAAHgNADQgMAEgGADQgGADgPAPIgCACIgGAHIgCADQAAADAPAVIACACIAeAkQAMAPAHAEQAEADALAEQALADAAAHQAAAIgIADQgIADgSAAg");
	this.shape_1.setTransform(58.6,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AAfBRIgJgJIgIAEQgUAOgWAAQgZAAgQgOQgPgPAAgYQgBgbAVgPQAUgPAkAAQAIAAAFACQAEADAAAGQAAAKgMAAQgQAAgLAIQgLAIABAPQAAAOAJAIQAIAIAQAAQAQAAAHgHQAHgIAAgSIAAhBQAAgPgGgIQgHgIgLAAQgJAAgHADQgHAEgHAIIgEAEQgLAOgLAAQgHAAgEgFQgEgEAAgIQAAgQAUgLQAUgLAfAAQATAAAOAFQAOAFAHAKQAFAGADALQABAKAAAZIAAA3QABAKABAFQACAEAEABIAEACQAMADAAAGQAAAIgMAHQgMAGgPAAQgIAAgIgJg");
	this.shape_2.setTransform(39.3,4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("ABBB6QgKgDAAgIQAAgHALgEIAHgEQAEgCABgIQABgHAAgXIAAgJIAAhJIgBgsIgWA5QgzCEgLAAQgFAAgKgSQgKgSgYg4IgmhXIgBBEIgBAvIABAgQABAHADACIAHAEQALAEAAAHQAAAIgJADQgJADgVAAQgTAAgIgDQgJgEAAgHQAAgGAKgEQAJgFABgDQACgJADgsQADgsAAg2IAAgGQAAgSgCgGQgBgGgEgDIgIgDQgMgFAAgHQAAgGAIgDQAIgDAZAAIAZABIAHABQADADAMAfIAKAYIAFAMQAqBoADAAQADAAAQgmQAPgkAWg9IADgKQAGgTAGgGQADgDAGgBIAYgCQAXAAAIADQAIADAAAGQAAAIgKADIgFACQgFADgCAHQgCAHAAAaIACBiQACAsABAHQABAEAIADIAEABIAHAEQACACAAAEQAAAIgKADQgKADgcAAQgaAAgJgDg");
	this.shape_3.setTransform(14.2,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgcB8QgJgDAAgHQAAgGAHgDIAJgEQADgDABgLIABgiIAAgbIAAggIAAgNQAAgsgBgMQgCgMgEgDIgKgEQgLgDAAgGQAAgEADgDQAEgDAMgEIAXgGIARgDQAFAAACAEQADACAAAJIgBANQgCA+AAA9IABA8QABAMADAEIAKAEQAIADAAAHQAAAGgJADQgIADgXAAQgZAAgIgDg");
	this.shape_4.setTransform(-16,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgcB8QgJgDAAgHQAAgGAHgDIAJgEQADgDABgLIABgiIAAgbIAAggIAAgNQAAgsgBgMQgCgMgEgDIgKgEQgLgDAAgGQAAgEADgDQAEgDAMgEIAXgGIARgDQAFAAACAEQADACAAAJIgBANQgCA+AAA9IABA8QABAMADAEIAKAEQAIADAAAHQAAAGgJADQgIADgXAAQgZAAgIgDg");
	this.shape_5.setTransform(-25.6,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgCAyIgMhLIgBgDIAAgEQAAgIAEgFQAEgEAHAAQAIAAAEAEQAEAFAAAIIAAAFIgBACIgMBLg");
	this.shape_6.setTransform(-33.1,-6.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_7.setTransform(-45.2,4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AAYA8IglhfQgLgfgGgPQgIgOgGgFIgKgEQgJgDAAgHQABgHAHgCQAIgDAiAAQAfAAAIADQAIACAAAHQAAAHgNAFIgCAAQgEACgBACQgCADAAAEQAAAGAIAXIAdBLIALAcQAEAHADAAQACAAAEgFIAMgaIACgHQAlhVgBgLQAAgFgCgEQgDgEgFgCIgFgCQgJgEgBgHQAAgHAHgCQAHgDAdAAQAbAAAHADQAHACAAAHQAAAHgKAEIgHAEQgMAIgXA7IgPAjIghBRIgFAQQgLAbgIAAQgIAAgahDgAhHBxIgCgGQgWgwgihYIgQgpIgKgVQgEgHgGgDIgFgCQgLgEAAgHQAAgHAIgCQAJgDAgAAQAhAAAIADQAIACAAAHQAAAHgOAFIgBAAQgEACgCACQgCADAAAEQAAAFAHAVIAdBMIAOAfQADAGADAAQADAAADgIIAJgUQAEgLAJAAQALAAAAALIgCALIgXA3IgEANQgMAcgGAAQgHAAgGgOg");
	this.shape_8.setTransform(-72.2,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmake, new cjs.Rectangle(-92,-22.5,180.1,45.1), null);


(lib.theuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape.setTransform(16.3,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AAYB8QgJgDAAgGQAAgHAJgDIAHgDQAEgCABgHQACgIAAgSQAAg4gHgNQgHgOgSAAQgJAAgIAGQgJAFgEAJQgEAHgBANQgCAOAAAhQAAASACAGQABAFAEACIAGADQAJADAAAHQAAAGgJADQgIADgWAAQgcAAgIgDQgIgDAAgHQAAgGAIgDIAFgCQAEgDACgHQACgHAAgTIAAgcIAAgbIgBhNQgBgTgDgEQgBgCgLgDQgKgDAAgGQAAgFAEgDQAFgDAPgGIARgFIAQgCQAGAAACAEQADADAAAIIgBAHIgBBFIAAAIIABAEIACACIAEgEIAGgHQAJgJAKgEQAJgEAKAAQAeAAAPATQAOATAAAmIAAAQIABAfIAAAKQAAAJABAEQACAEAEACIAEACQAJADAAAGQAAAHgIADQgJADgbAAQgXAAgIgDg");
	this.shape_1.setTransform(-3.4,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_2.setTransform(-19.4,2.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.theuse, new cjs.Rectangle(-27.6,-22.5,55.3,45.1), null);


(lib.theturkeyuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AhPByQgIgHAAgLQAAgIAGgHQAGgGAIAAIAIABIAFAEIAFAHQAEAHAEAAQAJAAAJgNQAJgNAAgNQAAgPgMgcIgCgEIgcg8IgQghQgDgGgKgFIAAAAQgGgCgCgCQgCgDAAgEQAAgHAJgDQAJgDAZAAQAaAAAIADQAIACAAAHIgBAGIgDADIgGADQgHACAAADIAEANIAOAjIANAgQAFAJACAAQACAAAEgJIALgbIANgiQAEgMAAgFQAAgFgKgFQgKgGAAgEQAAgGAIgDQAIgCAUAAQAVAAAHADQAHACAAAHQAAAHgKACIgHACQgKAGgLAdIgFANIgWA3QgcBIgSAWQgSAVgZAAQgNAAgIgHg");
	this.shape.setTransform(77.3,7.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_1.setTransform(59.4,4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AA4B/IgHgCQgHgDgRgUIgHgKIgDgEQgqg2gDAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAIAAAHIAAAHIABAlQABAKACAEIAKAEQAIADAAAHQAAAGgJADQgIADgXAAQgaAAgIgDQgJgDAAgHQAAgGAJgDIAEgCQAFgCACgJQABgIAAgUIAAgWIAAgbIAAgUIgBhAQgBgRgDgCQgCgDgHgCIgGgBIgHgDIgBgGQAAgEADgDQAEgDAMgEIAXgGIASgDQAFAAACAEQADACAAAJIgBAhIgBAtIAAArIAAAJQABAAAAAAQAAAAAAABQABAAAAAAQAAAAABAAIAHgEIANgKIAQgRQAEgEAAgDQAAgBgGgEQgFgDAAgFQAAgJAIgCQAJgEAYAAQAQAAAIAEQAIADAAAHQAAAHgNADQgMAEgGADQgGADgPAPIgCACIgGAHIgCADQAAADAPAVIACACIAeAkQAMAPAHAEQAEADALAEQALADAAAHQAAAIgIADQgIADgSAAg");
	this.shape_2.setTransform(41.2,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("Ag0BWQgIgDAAgHQAAgHAIgCIAFgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgLQAAgegCgKQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgDQAIAAADAXIAAAEIABAAQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgGQgBgFgCAAQgMAAgFAQQgEARAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKADgXgBQgaABgJgDg");
	this.shape_3.setTransform(24.8,3.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AAmBYQgDgDAAgGIAAgMIAAgBIgBAAQgCAAgEAEIgDADQgHAIgLAFQgKAEgMAAQgOAAgLgFQgLgFgHgJQgJgKgDgOQgEgOAAgkIAAgMIAAgMIAAgEQAAgOgCgEQgBgEgHgCIgHgCQgJgDAAgGQAAgEAEgDQADgDAMgEIAXgHIATgCQAFAAACADQABAEAAAHIAAAHIgBBBQAAAiAHAOQAHANASAAQASAAAKgRQAIgSAAgpIAAgNQAAgOgCgEQgCgEgGgCIgHgCQgJgDAAgGQgBgEAEgDQADgDANgEIAWgHIASgCQAGAAACADQACADAAAIIgBAKIgCBGIABAeIABALQABAHAJAEIAAAAIAEABQAJADAAAGQAAAEgDADQgDACgIADIgYAIQgMADgGAAQgFAAgCgCg");
	this.shape_4.setTransform(7.3,4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgkB7QgJgDgBgIQAAgHAKgDQAJgEACgCQACgDABgdIABhRIAAgtIgCgcQAAgFgEgBQgCgCgIAAIgHAAQgMAAgHADQgGADgFAHIgGALIgEAMIgGAFQgDACgCAAQgGAAgCgEQgCgFAAgKQgBgXAGgOQAFgOAJAAIACAAQANACAVAAIBlAAQAVAAAOgCIABAAQAJAAAGAOQAEAOAAAXQAAAKgCAFQgCAEgGAAIgGgCIgEgFIgGgMIgFgLQgEgHgIgDQgGgDgNAAIgGAAQgHAAgEACQgCABgBAFIgBAcIgBAtIABBRQABAdACADQACACAJAEQAKADAAAHQAAAIgLADQgJADgbAAQgaAAgKgDg");
	this.shape_5.setTransform(-14,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_6.setTransform(-43.9,4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AAYB8QgJgDAAgGQAAgHAJgDIAHgDQAEgCABgHQACgIAAgSQAAg4gHgNQgHgOgSAAQgJAAgIAGQgJAFgEAJQgEAHgBANQgCAOAAAhQAAASACAGQABAFAEACIAGADQAJADAAAHQAAAGgJADQgIADgWAAQgcAAgIgDQgIgDAAgHQAAgGAIgDIAFgCQAEgDACgHQACgHAAgTIAAgcIAAgbIgBhNQgBgTgDgEQgBgCgLgDQgKgDAAgGQAAgFAEgDQAFgDAPgGIARgFIAQgCQAGAAACAEQADADAAAIIgBAHIgBBFIAAAIIABAEIACACIAEgEIAGgHQAJgJAKgEQAJgEAKAAQAeAAAPATQAOATAAAmIAAAQIABAfIAAAKQAAAJABAEQACAEAEACIAEACQAJADAAAGQAAAHgIADQgJADgbAAQgXAAgIgDg");
	this.shape_7.setTransform(-63.6,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_8.setTransform(-79.7,2.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.theturkeyuse, new cjs.Rectangle(-87.9,-22.5,175.9,45.1), null);


(lib.thestuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AhABxQgVgOAAgTQAAgIAEgGQAFgGAJAAQAIAAADAEQAFAFACAIQAEAMALAIQALAHAVAAQAWAAAPgJQAQgJgBgNQAAgIgFgFQgGgEgKAAIgVABIgaACQgeAAgRgLQgRgKAAgOQABgJAFgIQAGgIANgHQgKgJgFgLQgFgLAAgOQAAgcAVgSQAVgTAhAAIARABIAbAGQAGAAAIgEQAHgDALgHIAFAFIADAGQAAAHgGAHQgFAHgLAFIAGAOIABAOQAAAdgUASQgWARggAAIgTgBIgQgEIgGAHIgBAGQAAAIAIAEQAIAEARAAIAagCIAbgCQAXAAAOAKQANAKgBASQABAcgcASQgbASgpAAQggAAgXgNgAgchVQgJALAAARQAAASAJALQAIAKAPAAQANAAAKgKQAKgLAAgSQAAgRgJgLQgKgLgOAAQgOAAgJALg");
	this.shape.setTransform(82.4,6.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AAXBWQgIgDAAgGQAAgHAIgDIAHgDQAEgCABgIQACgHAAgTQAAg2gHgOQgHgOgSAAQgJAAgIAGQgIAFgFAJQgEAIgBANQgCANAAAiQAAARACAGQABAFAEACIAGADQAJADAAAHQAAAGgIADQgJADgWgBQgbABgIgDQgJgDAAgHQAAgHAJgCIAEgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgRQAAgcgCgHQgBgJgDgCIgIgDQgLgDAAgGQAAgEADgDQAEgDAHgDIAZgIIASgDQAFAAACADQACADAAAFIAAALIAAACIABABIABgBIABAAIAEgDIAEgEQASgRAVgBQANAAALAGQAMAFAIAKQAIAJADANQADAOAAAbIAAAWIAAAMIAAAKQAAAMACAFQACAFAEACIAEADQAJACAAAHQAAAHgIADQgIACgbAAQgYABgIgDg");
	this.shape_1.setTransform(62.2,3.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgeB8QgJgDAAgIQAAgGAJgDIAEgCQAFgCABgGQADgGAAgNIgBgMIAAgNIAAgSQAAgcgCgHQAAgIgEgCIgIgDQgKgDAAgGQAAgEACgDQAEgDAHgDIAagIIASgEQAEAAACAEQACADAAAIIAAAKIAAAIIgBArIAAABIgBArQAAAQABAHQACAHAEACIAHACQAIAEABAGQAAAHgJADQgJACgWAAQgaAAgIgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgMAAQgKAAgIgGg");
	this.shape_2.setTransform(47,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgwB8QgJgDABgHQAAgFAIgDIAEgCQAEgCACgGQABgGABgOIAAgRIAAhTIgUAAQgEAAgCgBQgBgCAAgFIAAgEQAAgFACgBQABgCAFAAIASAAIgCgOIAAgMQAAgbAPgOQAQgPAbAAQAVAAAMAJQAMAJAAAOQAAAIgEAEQgFAEgJAAQgFAAgEgCQgEgDgEgEIgDgHQgGgMgLAAQgGAAgDAEQgEAEAAAHIAEAUQADAPAAAMIAZAAQAFAAACABQABACAAAFIAAAEQAAAEgBACQgCACgFAAIgZAAIAABYQAAAXACAGQABAHAEACIAHACQAKAEAAAHQAAAGgJADQgIADgZAAQgZAAgIgDg");
	this.shape_3.setTransform(38.8,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgwB8QgIgDAAgHQgBgFAJgDIAEgCQAEgCACgGQABgGAAgOIAAgRIAAhTIgTAAQgEAAgCgBQgBgCAAgFIAAgEQAAgFACgBQACgCAEAAIASAAIgCgOIAAgMQAAgbAPgOQAQgPAbAAQAVAAAMAJQAMAJAAAOQAAAIgEAEQgFAEgJAAQgFAAgEgCQgFgDgDgEIgDgHQgGgMgLAAQgGAAgDAEQgEAEAAAHIAEAUQADAPABAMIAYAAQAFAAABABQACACAAAFIAAAEQAAAEgCACQgBACgFAAIgYAAIAABYQAAAXABAGQACAHADACIAHACQAKAEAAAHQAAAGgJADQgIADgZAAQgYAAgJgDg");
	this.shape_4.setTransform(29,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AAlBYQgCgDAAgGIAAgMIAAgBIgBAAQgCAAgEAEIgCADQgJAIgKAFQgKAEgMAAQgNAAgMgFQgLgFgIgJQgIgKgDgOQgEgOABgkIAAgMIAAgMIAAgEQAAgOgDgEQgCgEgFgCIgHgCQgKgDAAgGQAAgEADgDQAEgDAMgEIAXgHIATgCQAEAAACADQACAEAAAHIAAAHIgCBBQAAAiAIAOQAHANASAAQASAAAJgRQAJgSAAgpIAAgNQAAgOgCgEQgCgEgGgCIgHgCQgJgDAAgGQAAgEADgDQADgDAMgEIAYgHIASgCQAFAAACADQACADAAAIIAAAKIgDBGIABAeIABALQACAHAIAEIABAAIACABQAKADAAAGQAAAEgDADQgDACgHADIgZAIQgMADgGAAQgFAAgDgCg");
	this.shape_5.setTransform(12.1,4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_6.setTransform(-4.1,2.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgqB8QgTgDgNgIQgGgEgFgOQgEgPAAgUQAAgIADgEQADgEAFAAQAIAAAJAQIAEAHQALATANAJQANAIASAAQASAAANgLQANgLAAgRQAAgYgygWIgGgDQgqgRgNgQQgOgPAAgYQAAgfAXgUQAXgUAkAAIAUACIAYAFIAHgFIAGgBQAEAAADADQAEACADAHQAGAKAEAMQADALAAAJQAAAFgDAEQgDADgEAAQgKAAgIgNIgDgCQgKgNgLgGQgMgHgOAAQgTAAgLAJQgLAJAAAQQAAAOAJAJQAKAKAkAPIAHADQAfANAOAMQAJAJAFALQAFAMAAAOQAAAjgYAUQgZAUgrAAQgVAAgTgFg");
	this.shape_7.setTransform(-20.4,0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_8.setTransform(-49,4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AAYB8QgJgDAAgGQAAgHAJgDIAHgDQAEgCABgHQACgIAAgSQAAg4gHgNQgHgOgSAAQgJAAgIAGQgJAFgEAJQgEAHgBANQgCAOAAAhQAAASACAGQABAFAEACIAGADQAJADAAAHQAAAGgJADQgIADgWAAQgcAAgIgDQgIgDAAgHQAAgGAIgDIAFgCQAEgDACgHQACgHAAgTIAAgcIAAgbIgBhNQgBgTgDgEQgBgCgLgDQgKgDAAgGQAAgFAEgDQAFgDAPgGIARgFIAQgCQAGAAACAEQADADAAAIIgBAHIgBBFIAAAIIABAEIACACIAEgEIAGgHQAJgJAKgEQAJgEAKAAQAeAAAPATQAOATAAAmIAAAQIABAfIAAAKQAAAJABAEQACAEAEACIAEACQAJADAAAGQAAAHgIADQgJADgbAAQgXAAgIgDg");
	this.shape_9.setTransform(-68.7,0);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_10.setTransform(-84.8,2.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thestuffing, new cjs.Rectangle(-93,-22.5,186,45.1), null);


(lib.theside = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgNBaIgSgEIgFAEIgFABIgEgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgDAEQgDADgFAAQgDAAgEgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFgBAKQAAAHAHAGQAGAHAUAKIACABQAxAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape.setTransform(64.5,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_1.setTransform(47.9,4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AhLBpQgUgYAAglQAAgrAXgZQAXgbAlAAIAMACQAFABADAEQADAEAAAEQAAAKgLAAIgFgBIgEAAQgTAAgMAQQgLAOAAAcQAAAdAMASQANATATAAQASAAAKgKQAKgLAAgTIAAgvIAAhPQAAgMgDgFQgCgFgGgCIgFgBQgLgEAAgFQAAgFAEgDQAFgEANgEIATgGIAQgCQAGAAADADQACAEAAAIIAAAIIgCBqIABBIQABARADACIAMAEQAJACAAAGQAAAIgZAJIgRAEIgNABQgFAAgCgDQgCgCAAgGIAAgJIgBgCIgBgCIgFAEIgIAGQgKAHgJAEQgKAEgKAAQghAAgUgXg");
	this.shape_2.setTransform(29.2,0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgeB8QgJgDAAgIQAAgGAJgDIAEgCQAEgCADgGQACgGAAgNIgBgMIAAgNIAAgSQAAgcgBgHQgCgIgDgCIgIgDQgLgDAAgGQAAgEADgDQAEgDAIgDIAZgIIASgEQAEAAACAEQACADAAAIIAAAKIAAAIIgBArIAAABIgBArQAAAQABAHQACAHAEACIAHACQAIAEABAGQAAAHgJADQgJACgWAAQgZAAgJgCgAgVhWQgHgGAAgJQAAgKAIgHQAIgHAMAAQAKAAAIAGQAHAHAAAJQAAAJgIAHQgIAHgMAAQgKAAgIgGg");
	this.shape_3.setTransform(13.4,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgqB8QgTgDgNgIQgGgEgFgOQgEgPAAgUQAAgIADgEQADgEAFAAQAIAAAJAQIAEAHQALATANAJQANAIASAAQASAAANgLQANgLAAgRQAAgYgygWIgGgDQgqgRgNgQQgOgPAAgYQAAgfAXgUQAXgUAkAAIAUACIAYAFIAHgFIAGgBQAEAAADADQAEACADAHQAGAKAEAMQADALAAAJQAAAFgDAEQgDADgEAAQgKAAgIgNIgDgCQgKgNgLgGQgMgHgOAAQgTAAgLAJQgLAJAAAQQAAAOAJAJQAKAKAkAPIAHADQAfANAOAMQAJAJAFALQAFAMAAAOQAAAjgYAUQgZAUgrAAQgVAAgTgFg");
	this.shape_4.setTransform(-1.6,0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_5.setTransform(-30.2,4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AAYB8QgJgDAAgGQAAgHAJgDIAHgDQAEgCABgHQACgIAAgSQAAg4gHgNQgHgOgSAAQgJAAgIAGQgJAFgEAJQgEAHgBANQgCAOAAAhQAAASACAGQABAFAEACIAGADQAJADAAAHQAAAGgJADQgIADgWAAQgcAAgIgDQgIgDAAgHQAAgGAIgDIAFgCQAEgDACgHQACgHAAgTIAAgcIAAgbIgBhNQgBgTgDgEQgBgCgLgDQgKgDAAgGQAAgFAEgDQAFgDAPgGIARgFIAQgCQAGAAACAEQADADAAAIIgBAHIgBBFIAAAIIABAEIACACIAEgEIAGgHQAJgJAKgEQAJgEAKAAQAeAAAPATQAOATAAAmIAAAQIABAfIAAAKQAAAJABAEQACAEAEACIAEACQAJADAAAGQAAAHgIADQgJADgbAAQgXAAgIgDg");
	this.shape_6.setTransform(-49.9,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_7.setTransform(-66,2.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.theside, new cjs.Rectangle(-74.2,-22.5,148.4,45.1), null);


(lib.thedesserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgMBaIgTgEIgFAEIgFABIgEgBIgDgDQgGgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQAMgBAGgFQAHgGAAgJQAAgPgcgOIgKgFQgbgNgJgLQgKgLAAgRQAAgWAPgOQAQgPAZAAIALABIANADIAIgEIAFgBQAJAAAIAOQAIANAAAPQAAAGgCAEQgEADgEAAQgFAAgDgDQgEgDgFgIQgHgMgHgEQgGgDgKAAQgKgBgFAGQgHAFAAAKQABAHAGAGQAGAHAVAKIABABQAxAXAAAcQAAAYgTARQgSAQgcAAg");
	this.shape.setTransform(89.4,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_1.setTransform(75.9,2.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("Ag0BWQgIgDAAgHQAAgHAIgCIAFgDQAEgCACgFQACgHAAgNIAAgMIAAgNIAAgLQAAgegCgKQgBgJgEgDIgIgDQgKgDAAgGQAAgEADgDQADgDAIgDIAXgHIAQgDQAIAAADAXIAAAEIABAAQAJgOAJgHQAKgIAKAAQAMAAAHAIQAHAHAAAMQAAAMgFAHQgGAHgKAAIgIgCIgIgFIgEgGQgBgFgCAAQgMAAgFAQQgEARAAA0QAAAPABAHQACAIAFACIAHACQAKADAAAIQAAAGgJADQgKADgXgBQgaABgJgDg");
	this.shape_2.setTransform(63.5,3.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_3.setTransform(47.4,4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgNBaIgSgEIgFAEIgFABIgEgBIgEgDQgFgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgKgLQgJgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAGgBQAIAAAIAOQAIANAAAPQAAAGgCAEQgEADgFAAQgDAAgEgDQgEgDgGgIQgGgMgGgEQgIgDgJAAQgJgBgHAGQgFAFgBAKQAAAHAHAGQAGAHAUAKIACABQAxAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_4.setTransform(30.7,4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgNBaIgSgEIgFAEIgFABIgEgBIgDgDQgGgEgFgOQgFgOAAgNQAAgGADgDQADgEAEAAQAIAAAIAOIAHAKQAFAHAJAFQAJADAJABQALgBAIgFQAGgGAAgJQAAgPgcgOIgKgFQgbgNgJgLQgKgLAAgRQAAgWAQgOQAPgPAZAAIAMABIAMADIAIgEIAFgBQAJAAAIAOQAIANAAAPQAAAGgCAEQgEADgFAAQgDAAgEgDQgEgDgGgIQgFgMgHgEQgIgDgJAAQgJgBgHAGQgFAFgBAKQAAAHAHAGQAGAHAUAKIACABQAxAXAAAcQAAAYgSARQgTAQgcAAg");
	this.shape_5.setTransform(15.8,4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_6.setTransform(-0.8,4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AglB8IgWAAIgOAAIgOAAQgVAAgHgCQgGgDgBgHQAAgHAJgEQAKgDABgCQACgEACgaIAChDIgCg/QgCgbgCgDQgBgCgKgEQgJgEAAgHQAAgHAIgCQAHgEAVAAIAPABIARAAIAXgBIATAAQBBAAAiAhQAkAhgBA9QABA8glAfQgjAfhEAAgAgmhiQgHADgCAFQgCAHgBAUIgCA1IACBBQABAbACAGQABAFAMAEQALADAQAAQAnAAAUgXQAUgYAAgxQAAgzgXgaQgXgbgpAAQgOAAgJACg");
	this.shape_7.setTransform(-23.3,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("Ag3BBQgZgZAAglQAAgoAZgaQAagaAmAAQAhAAAUATQATATAAAgQAAALgDADQgDAEgNAAIhBAAQgGAAgDgDQgDgDAAgFQAAgEADgDQADgCAFAAIAkAAIAJgBQACgCAAgEQAAgQgLgMQgMgLgPAAQgVAAgKASQgJASAAAZQAAAaANAUQAOAUAVAAQANAAAJgDQAJgDAIgGIAGgFQAJgHAFAAQADAAADADQACACAAAEQAAAEgEAGQgEAGgIAGQgPAMgOAGQgOAFgQAAQgkAAgYgZg");
	this.shape_8.setTransform(-55.1,4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AAYB8QgJgDAAgGQAAgHAJgDIAHgDQAEgCABgHQACgIAAgSQAAg4gHgNQgHgOgSAAQgJAAgIAGQgJAFgEAJQgEAHgBANQgCAOAAAhQAAASACAGQABAFAEACIAGADQAJADAAAHQAAAGgJADQgIADgWAAQgcAAgIgDQgIgDAAgHQAAgGAIgDIAFgCQAEgDACgHQACgHAAgTIAAgcIAAgbIgBhNQgBgTgDgEQgBgCgLgDQgKgDAAgGQAAgFAEgDQAFgDAPgGIARgFIAQgCQAGAAACAEQADADAAAIIgBAHIgBBFIAAAIIABAEIACACIAEgEIAGgHQAJgJAKgEQAJgEAKAAQAeAAAPATQAOATAAAmIAAAQIABAfIAAAKQAAAJABAEQACAEAEACIAEACQAJADAAAGQAAAHgIADQgJADgbAAQgXAAgIgDg");
	this.shape_9.setTransform(-74.8,0);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AgIBoQgJgDgGgGQgGgFgDgKQgCgJAAgaIAAhcIgQAAIgFgBIgCgFIAAgEQAAgGASgPIAHgGIAHgGQASgQAHAAIAEACQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAgIAnAAQAEAAACACQABABAAAFIAAAEQAAAFgBACQgCACgEAAIgkAAIgDABIgBAEIAABVQAAAXAEAFQAEAGAKAAQAGAAAIgDIAMgDQAEAAACADQADACAAADQAAAKgPAJQgPAJgSAAQgKAAgIgDg");
	this.shape_10.setTransform(-90.9,2.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thedesserts, new cjs.Rectangle(-99.1,-22.5,198.2,45.1), null);


(lib.square = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#99CC33").ss(1,1,1).p("A3UxxMAupAAAMAAAAjjMgupAAAg");
	this.shape.setTransform(0.2,0.5,1.003,1.096);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("A3URxMAAAgjhMAupAAAMAAAAjhg");
	this.shape_1.setTransform(0.2,0.5,1.003,1.096);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#99CC33").ss(1,1,1).p("AAASIMAAAgkP");
	this.shape_2.setTransform(-149.9,-9.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.9,-126.1,301.9,252.4);


(lib.rolls = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.cinamonrolls();
	this.instance.parent = this;
	this.instance.setTransform(-46,-92);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.rolls, new cjs.Rectangle(-46,-92,92,184), null);


(lib.potatoesshadow_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.potatoesshadow();
	this.instance.parent = this;
	this.instance.setTransform(-59,-42.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.potatoesshadow_1, new cjs.Rectangle(-59,-42.5,118,85), null);


(lib.potatoeslowerleft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.potatoeswellmakethefeast();
	this.instance.parent = this;
	this.instance.setTransform(-54.5,-50);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.potatoeslowerleft, new cjs.Rectangle(-54.5,-50,109,100), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAVAqIgVhDIAAAAIgUBDIgMAAIgZhTIANAAIATBCIAUhCIAMAAIAUBCIAThCIAMAAIgZBTg");
	this.shape.setTransform(-33.6,-8.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgJAsIgIgDQgJgDgFgGQgHgGgCgIQgEgJAAgJQAAgJAEgJQACgIAHgFQAFgGAJgDIAIgDIAJAAQAJAAAJADIAHADIAHAGQAGAFAEAIQADAJAAAJQAAAJgDAJQgEAIgGAGIgHAGIgHADQgJADgJAAIgJAAgAgMgfQgHADgDAFQgEAFgDAGQgCAGAAAGQAAAHACAGQADAGAEAFQAEAFAGACQAFADAHAAQAHAAAGgDQAGgCAFgFQADgFADgGQACgGAAgHQAAgGgCgGQgDgGgDgFQgFgFgFgDQgHgCgHAAQgHAAgFACg");
	this.shape_1.setTransform(-44.7,-8.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAVAqIgshEIAAAAIAABEIgMAAIAAhTIAPAAIAsBCIAAAAIAAhCIAMAAIAABTg");
	this.shape_2.setTransform(-54.6,-8.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAQAqIgVgmIgNAAIAAAmIgLAAIAAhTIAbAAQAFgBAFACQAGABAEADQAEACADAFQACAEAAAHQAAAKgGAFIgGAEIgJADIAYAmgAgSgEIAOAAIAHgBQAEgBACgBIAFgFQABgCAAgEQAAgEgBgCIgFgFIgGgCIgGAAIgPAAg");
	this.shape_3.setTransform(-66,-8.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAqIAAhTIA2AAIAAAKIgqAAIAAAaIAnAAIAAAJIgnAAIAAAcIArAAIAAAKg");
	this.shape_4.setTransform(-73.6,-8.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkAqIAAhTIAcAAQAIgBAIADQAIADAGAFQAHAFAEAHQACAFABAEIABAKIgBAKQgBAFgCAEIgFAHIgGAGQgGAFgIADQgKADgGgBgAgZAgIAPAAQAIAAAFgCQAHgDAFgEQAFgEACgGIACgGIABgHIgBgGIgCgHQgCgGgFgEQgFgEgHgCQgFgCgIAAIgPAAg");
	this.shape_5.setTransform(-81.9,-8.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAQAqIgVgmIgNAAIAAAmIgLAAIAAhTIAbAAQAFgBAFACQAGABAEADQAEACADAFQACAEAAAHQAAAKgGAFIgGAEIgJADIAYAmgAgSgEIAOAAIAHgBQAEgBACgBIAFgFQABgCAAgEQAAgEgBgCIgFgFIgGgCIgGAAIgPAAg");
	this.shape_6.setTransform(-90.2,-8.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgJAsIgIgDQgJgDgFgGQgHgGgCgIQgEgJAAgJQAAgJAEgJQACgIAHgFQAFgGAJgDIAIgDIAJAAQAKAAAIADIAHADIAHAGQAGAFADAIQAEAJAAAJQAAAJgEAJQgDAIgGAGIgHAGIgHADQgIADgKAAIgJAAgAgMgfQgHADgDAFQgFAFgCAGQgCAGAAAGQAAAHACAGQACAGAFAFQAEAFAGACQAFADAHAAQAHAAAGgDQAGgCAEgFQAEgFADgGQACgGAAgHQAAgGgCgGQgDgGgEgFQgEgFgFgDQgHgCgHAAQgHAAgFACg");
	this.shape_7.setTransform(-99.5,-8.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-106.6,-17.6,81.4,18.8), null);


(lib.orangefruitbowl = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.fruitorangebowl();
	this.instance.parent = this;
	this.instance.setTransform(-47.5,-30.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.orangefruitbowl, new cjs.Rectangle(-47.5,-30.5,95,61), null);


(lib.logokale = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(130.4,59.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgUgDgIgEQgJgFAAgNQAAgKAGgHQAFgHAJAAIARAAQAKAAAFgLQADgKgBgXIAAl5QABgXgDgKQgFgLgKAAIgRAAQgJAAgFgHQgGgHAAgKQAAgNAJgFQAIgEAUgDQBegNBrAAQBNAAA1ASQA1ASAnAoQAlAlAVA5QATA4AABEQAABNgZA9QgZA+gwAlQglAegvAOQgxAOhEAAQhrAAhegNgAgvjrQgcAFgKALQgKAMAAAhIAAFjQAAAhAVALQANAHAnADQBNAEAshAQAqg/ABhwQAAhwgrg/Qgrg/hKAAIgdADg");
	this.shape_1.setTransform(62.2,30.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(81.2,88.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(52.4,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(22.6,88.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAvBeIghgxQgFgJgKAAIgtAAQgEAAgDADQgDACgBAFIABAwQAAAHgKACIgPAAQgNAAAAgLIAAi6QAAgIAJAAIBrAAQAgAAAUASQAVAUgBAgQAAAXgOAPQgIAJgPAJQgHAIAEAFIAiAyQAFAHgFAFQgEAEgPAAQgRAAgFgJgAg5g4IAAAuQABAFAEADQAEACAFAAIA+AAQAQAAALgHQALgKAAgPQAAgRgLgJQgLgJgQAAIg+AAQgOAAAAALg");
	this.shape_5.setTransform(-11.1,88.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAgBABAAQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-44.3,88.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBlQgFgDAAgFIgOhrQgCgHgFAAQgDAAgDAEIgxA+QgEAFgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBpQgCAKgTAAQgGAAgFgCQgGgDAAgGIAVixQACgJADgCQAEgFALAAQAKAAAFAIIA4BPQAFAIAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAJIAVC1QABAKgXAAQgFAAgFgCg");
	this.shape_7.setTransform(-78.1,88.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(14.6,-54.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDxQhFg2gYheIgBgDQgCgLgHABQgGgBgCALIgBABQgYBghGA2QhIA2hoAAQh+AAhMhQQhMhRAAiFQAAiGBMhRQBLhQCAAAQBpAABHA2QBHA3AXBgQACALAGgBQAHAAACgLIABAAQAXhgBGg2QBHg2BoAAQB/AABNBPQBMBQAACGQAACHhMBRQhNBQiBAAQhmAAhHg2gACniqQgpA/AABtQAABtApA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/gAmFiqQgoA/AABtQAABtAoA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/g");
	this.shape_9.setTransform(-21,30.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-98.4,30.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIQAKgHAIAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(110.1,30.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAIQgNAIgQABQgTgBgKgIQgLgKgJgYIimm+QgKgZgHgIQgHgHgUgFQgOgBgFgGQgFgFAAgKQAAgXAdAAICvAAQAcAAAAAXQAAAMgHAEQgHAFgRABQgOACgGAEQgGAFAAALQAAAIADALIBzFGQACAFAFAAQAEgBACgFIA/i1QAIgZgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgEgGgEQgFgGAAgJQAAgaAdAAICnAAQAdAAAAAXQAAATgcAFQgRABgFAFQgGAFAAALQAAALAIAZIBfEsQACAFAEAAQAFgBABgFIBdk6QAEgLAAgJQAAgTgdgDQgbgCAAgWQAAgMAHgGQAIgGARAAIElAAQAVAAAIAGQAIAFAAAOQAAAKgGAHQgGAHgJAAIgQAAQgLAAgFAKQgCAJAAAZIAABuQAAAdAFAHQAGAGAXAAIB0AAQAXAAAHgHQADgEAAgGIABgfIAAhoQAAgbgDgHQgFgKgKAAIgQAAQgKAAgHgHQgGgHAAgKQAAgOAIgFQAJgGAWAAICaAAQAWAAAJAGQAJAFAAAOQAAAKgHAHQgGAHgJAAIgSAAQgEAAgEADQgFAEgBADQgDAKAAAYIAAF8QAAAYADALQABADAFAEQAEACAEAAIASAAQAJAAAGAIQAHAGAAAKQAAAOgJAGQgIAEgXAAIiaAAQgWAAgIgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIAQAAQAKABAFgKQADgIAAgbIAAh8IgBgdQAAgHgDgDQgHgIgXAAIh0AAQgXAAgGAHQgFAGAAAeIAACAQAAAZACAKQAFAKALgBIAQAAQAJAAAGAIQAGAGAAALQAAANgIAGQgIAEgVAAIiaAAQgWAAgJgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIARAAQAEAAAFgCQAEgEABgDQADgIAAgbIAAl8QAAgwgkAEQgLABgHAJQgIAKgGAVIiHGzQgJAfgKAMQgLAKgTABQgTAAgLgKg");
	this.shape_12.setTransform(-74.6,-36.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDACgEQADgIAAgXIAAmAQAAgZgDgHQgDgMgLAAIgRAAQgKABgGgHQgHgHAAgKQAAgOAJgFQAJgGAWAAICcAAQAWAAAJAGQAJAFAAAOQAAAKgGAHQgHAHgJgBIgSAAQgOAAgDAMQgDAFAAAbIAAFkQAAAdACAJQACAJAIAFQAGAFALABQALACAaAAIAwAAQAvAAAPggIAIgQQAIgPAPAAQAMgBAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(69.2,-37.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgaAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(114.4,-37.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logokale, new cjs.Rectangle(-175,-175,350,350), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("A2aygMAs1AAAMAAAAlBMgs1AAAg");
	this.shape.setTransform(0,0,1.042,1.051);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-150.5,-125.5,301,251), null);


(lib.greenvegetables_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.greenvegetables();
	this.instance.parent = this;
	this.instance.setTransform(-68.5,-75.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.greenvegetables_1, new cjs.Rectangle(-68.5,-75.5,137,151), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("ApwCYIAAkwIThAAIAAEwg");
	this.shape.setTransform(-15.7,0,1,0.934);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-78.2,-14.2,125,28.5), null);


(lib.cranberriesshadow_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.cranberriesshadow();
	this.instance.parent = this;
	this.instance.setTransform(-49,-35);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cranberriesshadow_1, new cjs.Rectangle(-49,-35,95,69), null);


(lib.buttonmain = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.square("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.1,0);
	this.instance._off = true;
	this.instance.filters = [new cjs.ColorFilter(0, 0, 0, 1, 0, 110, 71, 0)];
	this.instance.cache(-153,-128,306,256);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


// stage content:
(lib.squareholidaymains = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_247 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(247).call(this.frame_247).wait(8));

	// button
	this.btn_main = new lib.buttonmain();
	this.btn_main.parent = this;
	this.btn_main.setTransform(149.5,124.2);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.buttonmain(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(255));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(255));

	// white-square
	this.instance_1 = new lib.whitesquare();
	this.instance_1.parent = this;
	this.instance_1.setTransform(153,126.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(246));

	// kale-logo
	this.instance_2 = new lib.logokale();
	this.instance_2.parent = this;
	this.instance_2.setTransform(250.8,32.8,0.003,0.003);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.24,scaleY:0.24,alpha:1},6,cjs.Ease.get(1)).to({regY:0.2,scaleX:0.22,scaleY:0.22},7,cjs.Ease.get(1)).wait(233));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AySMlIAAyHMAnNAAAIAASHg");
	mask.setTransform(133.9,80.5);

	// well make the feast
	this.instance_3 = new lib.wellmakethefeast();
	this.instance_3.parent = this;
	this.instance_3.setTransform(103.4,96.5);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(216).to({x:-77.2},0).to({x:108.4,alpha:1},10,cjs.Ease.get(1)).to({x:103.4},8,cjs.Ease.get(1)).wait(21));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AySMlIAAyHMAnNAAAIAASHg");
	mask_1.setTransform(133.9,80.5);

	// YOU-TAKE-THE-CREDIT
	this.instance_4 = new lib.youtakethecredit();
	this.instance_4.parent = this;
	this.instance_4.setTransform(88.3,145);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(226).to({x:-93.8},0).to({x:98.3,alpha:1},10,cjs.Ease.get(1)).to({x:88.3},8,cjs.Ease.get(1)).wait(11));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AySMlIAAyHMAnNAAAIAASHg");
	mask_2.setTransform(133.9,80.5);

	// well-make
	this.instance_5 = new lib.wellmake();
	this.instance_5.parent = this;
	this.instance_5.setTransform(105.4,88.8);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(9).to({x:-103.6,y:86.5},0).to({x:110.4,y:88.8,alpha:1},10,cjs.Ease.get(1)).to({x:105.4},8,cjs.Ease.get(1)).wait(179).to({alpha:0},5).wait(44));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("AySMlIAAyHMAnNAAAIAASHg");
	mask_3.setTransform(133.9,80.5);

	// the
	this.instance_6 = new lib.theuse();
	this.instance_6.parent = this;
	this.instance_6.setTransform(40.8,130.1);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(86).to({x:40.5,alpha:1},0).wait(120).to({alpha:0},5).wait(44));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("AySMlIAAyHMAnNAAAIAASHg");
	mask_4.setTransform(133.9,80.5);

	// the-turkey
	this.instance_7 = new lib.theturkeyuse();
	this.instance_7.parent = this;
	this.instance_7.setTransform(100.8,130.1);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(9).to({x:-105.7},0).to({x:105.8,alpha:1},10,cjs.Ease.get(1)).to({x:100.8},8,cjs.Ease.get(1)).wait(59).to({alpha:0},5).wait(164));

	// the-stuffing
	this.instance_8 = new lib.thestuffing();
	this.instance_8.parent = this;
	this.instance_8.setTransform(105.9,130.1);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(86).to({alpha:1},10).wait(30).to({alpha:0},5).wait(124));

	// the-sides
	this.instance_9 = new lib.theside();
	this.instance_9.parent = this;
	this.instance_9.setTransform(87.1,130.1);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(126).to({alpha:1},10).wait(30).to({alpha:0},5).wait(84));

	// the-desserts
	this.instance_10 = new lib.thedesserts();
	this.instance_10.parent = this;
	this.instance_10.setTransform(112,130.1);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(166).to({alpha:1},10).wait(30).to({alpha:0},5).wait(44));

	// order-now-mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("AnlPFIAAk+IVRAAIAAE+g");
	mask_5.setTransform(87.6,96.5);

	// order-now
	this.instance_11 = new lib.ordernow();
	this.instance_11.parent = this;
	this.instance_11.setTransform(143.7,184.5);
	this.instance_11.alpha = 0;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(19).to({x:17},0).to({x:146.7,alpha:1},10,cjs.Ease.get(1)).to({x:143.7},8,cjs.Ease.get(1)).wait(218));

	// cta-mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	mask_6.graphics.p("AqnPIIAAlUIX3AAIAAFUg");
	mask_6.setTransform(84.8,96.9);

	// cta-rectangle
	this.instance_12 = new lib.ctarectangle();
	this.instance_12.parent = this;
	this.instance_12.setTransform(95.1,176,1,1.058);
	this.instance_12.alpha = 0;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(19).to({x:-32.3},0).to({x:98.1,alpha:1},10,cjs.Ease.get(1)).to({x:95.1},8,cjs.Ease.get(1)).wait(218));

	// rolls
	this.instance_13 = new lib.rolls();
	this.instance_13.parent = this;
	this.instance_13.setTransform(254,92);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(66).to({alpha:1},10).wait(179));

	// fruit-bowl
	this.instance_14 = new lib.orangefruitbowl();
	this.instance_14.parent = this;
	this.instance_14.setTransform(187.5,30.5);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(61).to({alpha:1},10).wait(184));

	// potatoes
	this.instance_15 = new lib.potatoeslowerleft();
	this.instance_15.parent = this;
	this.instance_15.setTransform(54.5,200);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(56).to({alpha:1},10).wait(189));

	// cranberries-shadow
	this.instance_16 = new lib.cranberriesshadow_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(196.5,219);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(41).to({alpha:1},10).wait(204));

	// green-vegetable
	this.instance_17 = new lib.greenvegetables_1();
	this.instance_17.parent = this;
	this.instance_17.setTransform(231.5,174.5);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(51).to({alpha:1},10).wait(194));

	// potatoes-top-left
	this.instance_18 = new lib.potatoesshadow_1();
	this.instance_18.parent = this;
	this.instance_18.setTransform(59,42.5);
	this.instance_18.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(46).to({alpha:1},10).wait(199));

	// table-tan
	this.instance_19 = new lib.squareholidaymainstable();
	this.instance_19.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(255));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(144.1,118.1,318,266);
// library properties:
lib.properties = {
	id: '92879F2740E34FB9890B82961B713FEA',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['92879F2740E34FB9890B82961B713FEA'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;